### ISSUE TITLE
Numbers in graphs don't match table

### ISSUE THREAD

**Issue by joneschrisg** [rocallahan/rr-paper#1]
Figure 2: `cp` no-syscallbuf overhead caps at ~14, but is 23.7x in the table.  And in Figure 3, `make` and `htmltest` are capped for DynamoRio.  I'm guessing you're doing this on purpose, but that's not obvious to a reader just skimming through the paper.  You could achieve both goals with a "broken-bar" chart like [this](http://peltiertech.com/images/2011-11/Ybroken.png).

(Filing issue because I'm not sure how you're generating the graphs)

**Comment by rocallahan** [comment]
I'm using LibreOffice Calc. It doesn't seem to have a satisfactory solution to this problem. I think the best approach might be to manually position text labels at the tops of the cut-off columns showing the real value. I'll see if I can do that.

**Comment by rocallahan** [comment]
I rewrote the graphs to use matplotlib and fixed this issue by changing the scale in figure 3 and adding a numeric label to the overflowing bar in Figure 2.
