### ISSUE TITLE
Show disk-space usage comparison to without optimizations

### ISSUE THREAD

**Issue by joneschrisg** [rocallahan/rr-paper#4]
Re: `[TODO: show a graph for space usage? Which one?]`, I would find this somewhat informative for each test case
- left bar: space usage with optimizations turned off, broken down by uncompressed general trace data, copied files, large block reads (?)
- right bar: same categories but with optimizations applied

But I'm not 100% convinced this is useful because it's tricky to show the real usage of copyref files.  Maybe hard to improve on what's there.

**Comment by rocallahan** [comment]
I could leave out cloned files altogether. But yeah, I have a feeling a graph won't add much value here.
