### ISSUE TITLE
Suggestions for extra tables/figures

### ISSUE THREAD

**Issue by joneschrisg** [rocallahan/rr-paper#5]
These tend to take long enough to make that I don't want to put in the time unless you agree they're worthwhile :).

<s>\- [ ] §2.4.1: trivial example of a asm program with indeterminate replay behavior</s>
- [x] §3: architecture diagram of rr tracer process, ptrace boundary, kernel, seccomp-bpf boundary, tracee process, tracee thread, syscallbuf library.  In the context of §3.{2,3,4} show the different control-flow paths that traced vs. untraced vs. untraced-desched calls make through the blocks.  My guess is that this is probably the most difficult part of rr to wrap ones head around, and also one of the most interesting things to know about it, so worth spending some time on IMO.

<s>\- [ ] §5: table summarizing known tradeoffs/limitations of rr given its implementation approach; the goal would be to make all the rr "asks" very clear with a clear "owner".  Displayed as
    0. tradeoff/limitation --- for example, detectable by tracees; CPUID fragility; no real shmem
    0. why does rr do it this way --- required for syscallbuf, so core part of approach; no CPUID virtualization; no HW memory traffic recording
    0. how can this be fixed --- better sandboxing APIs; kernel folks adding API for existing HW support; HW folks commercializing existing research</s> (out of space)

**Comment by rocallahan** [comment]
>  §2.4.1: trivial example of a asm program with indeterminate replay behavior

Not sure what you have in mind here. I don't think this will be worth it.

> §3: architecture diagram of rr tracer process, ptrace boundary, kernel, seccomp-bpf boundary, tracee process, tracee thread, syscallbuf library.

Yes, I think this is worth adding.

> §5: table summarizing known tradeoffs/limitations of rr given its implementation approach

Maybe, if we can produce something that's crisp and accurate.

**Comment by joneschrisg** [comment]
> >  §2.4.1: trivial example of a asm program with indeterminate replay behavior
> 
> Not sure what you have in mind here. I don't think this will be worth it.

I was thinking it could be useful to give power users an intuition of what kind of code rr would choke on, but thinking again it's hard to come up with even a toy example that does anything semi-useful.  So yeah probably not worth the space.

**Comment by joneschrisg** [comment]
> §3: architecture diagram of rr tracer process ...

Here's the sketch of what I have in mind.  Let me know what you think.  (Please ignore the formatting, totally unstyled.)

![syscall-ptrace](https://cloud.githubusercontent.com/assets/325916/14911841/f2731ae2-0dac-11e6-8434-52e0ec96022b.png)
Figure X:  Traditional traced syscall.  Starting at label (1), the Tracee task enters the kernel to make a `read` system call.  The system call is intercepted by the `ptrace` mechanism and the Recorder task is notified, which incurs a context switch.  At label (2), Recorder continues the system call, context-switching back to Tracee and resuming the call normally in the kernel's `sys_read()`.  At label (3), the `read` call result is ready, and `ptrace` intercepts the return value and notifies Recorder, incurring a third context switch.  Recorder records the results of the call.  At label (4), Recorder finishes the syscall, context-switching back into Tracee, and `read` call finishes.

![syscall-syscallbuf](https://cloud.githubusercontent.com/assets/325916/14911851/09930f02-0dad-11e6-97ac-fd71a26f43a0.png)
Figure Y:  Buffered system call.  The `syscallbuf` code injected into Tracee by Recorder decides to make an untraced syscall and enters the kernel.  The call is intercepted by `seccomp-bpf`, which determines that the call should continue without triggering a `ptrace` trap.  When the `read` call finishes, the `syscallbuf` records the results as described in (ref).

![syscall-blocked](https://cloud.githubusercontent.com/assets/325916/14912083/ccb70fd2-0dae-11e6-86e0-5adf4aa58aff.png)
Figure Z.  Buffered system call that blocked.  The `read` call begins as in Figure Y, but the kernel deschedules the Tracee task; usually because the `read` would block.  At label (1), the `perf` mechanism observes the descheduling of Tracee and raises a signal, which notifies Recorder by way of `ptrace` and incurs a context switch.  After this point, the `read` call will essentially complete as shown starting from label (2) in Figure X.

**Comment by rocallahan** [comment]
I think it might be easier to read if time proceeds uniformly linearly from top to bottom and we don't reenter blocks. That would also produce a diagram that better matches what the kernel looks like (there is no `ptrace` component that gets entered and reentered). The first diagram would then probably be easier to read because you don't have to study all the labels ... the fact that there are multiple labels `1' etc is also a problem.

In the last diagram you could show rr running another tracee after the first one has blocked.

**Comment by rocallahan** [comment]
> there is no ptrace component that gets entered and reentered

Well I guess there sort of is but it's just a notification/stopping mechanism rather than the big entity implied here. Not a big deal.

**Comment by joneschrisg** [comment]
> I think it might be easier to read if time proceeds uniformly linearly from top to bottom and we don't reenter blocks.

Yeah, that sounds better.

The squared boxes represent what would be real stack frames, actual function calls.  The rounded-corner boxes were just mechanisms that are more complicated than I wanted to try to explain here.  You're right that ptrace isn't a big entity but the syscall interception / stopping / notification code is just complex to explain.  I'll try to think of a better way to represent that; I think your timeline idea will help.  And other ideas welcome :).

**Comment by rocallahan** [comment]
Are you working on this or do you need me to take it over? This is the last outstanding item that I know of :-)

**Comment by joneschrisg** [comment]
I'm about a third of the way done with the revised diagrams, but it's been hard to find cycles the last few days.  Please feel free to take over! :)

**Comment by rocallahan** [comment]
OK, can you upload your latest somewhere?

**Comment by joneschrisg** [comment]
Sure.  I have some time tonight, so I'll push it along as far as I can and send you the results.
