### ISSUE TITLE
Diagram showing how rr fits into R&R "space"

### ISSUE THREAD

**Issue by joneschrisg** [rocallahan/rr-paper#6]
This one I'm not so sure about, but potentially helpful for a skimming reader to understand how rr fits in with past work without having to read all of §6.  I can imagine two:
1. { custom HW/SW setup vs. commodity } x { high overhead vs. low overhead }
   - The important comparison for rr --- it would be in the top right of "commodity" and "low overhead"
2. { general purpose use vs. specialized } x { limited vs. full-featured }
   - Introduces tradeoffs to support above --- rr is middle-towards-general-purpose, and middle-towards-full-featured.  But that's not bad; that discussion is pretty much already in §6.

**Comment by rocallahan** [comment]
I _think_ that section 6 already classifies related work clearly enough in the subsection headings that readers can navigate it quickly and adding a diagram won't add much. And adding a diagram gives people a chance to quibble about the placement of specific systems ("is X really lower overhead than Y?"). So I'll probably not do this.
